CREATE TABLE produits (
  id INT PRIMARY KEY,
  ref VARCHAR(50) NOT NULL,
  nom VARCHAR(100) NOT NULL,
  prix DECIMAL(10, 2) NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(255) NOT NULL,
  categorie VARCHAR(50) NOT NULL,
  stock INT(50) NOT NULL
);
